name = "CondMatRegistry"
uuid = "05b87536-5047-4b84-aee7-fc4a712cc979"
authors = ["Lukas Grunwald <lukas.grunwald@rwth-aachen.de>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
