name = "CondMatRegistry"
uuid = "fa72d679-44c2-4f33-8f7a-1b22ca4674e1"
repo = "git@github.com:lukasgrunwald/CondMatRegistry.git"
description = "Private repository containing (mainly) research code."

[packages]
8523ee09-f87b-436d-8687-f5a8240ec6b7 = { name = "MyPlot", path = "M/MyPlot" }
caac3ea5-a678-4878-8bc7-c03e822dd383 = { name = "GFFT", path = "G/GFFT" }
ddafdd3f-bffb-4613-bf4c-94e59b398e54 = { name = "PConv", path = "P/PConv" }
