name = "CondMatRegistry"
uuid = "fa72d679-44c2-4f33-8f7a-1b22ca4674e1"
repo = "git@github.com:lukasgrunwald/CondMatRegistry.git"
description = "Private repository containing (mainly) research code."

[packages]
57bfc871-17ad-47bf-8429-c0485d8290d3 = { name = "PrivateRegistryDebugger", path = "P/PrivateRegistryDebugger" }
8523ee09-f87b-436d-8687-f5a8240ec6b7 = { name = "MyPlot", path = "M/MyPlot" }
caac3ea5-a678-4878-8bc7-c03e822dd383 = { name = "GFFT", path = "G/GFFT" }
d27c24bd-84bf-4c52-914b-d12f8784db43 = { name = "LadderOperators", path = "L/LadderOperators" }
ddafdd3f-bffb-4613-bf4c-94e59b398e54 = { name = "PConv", path = "P/PConv" }
f2a00f92-3800-41f4-a80d-3c13bd45b518 = { name = "RegistryDebugger", path = "R/RegistryDebugger" }
